version: "3.4"
# Docker compose file used to load the TTS Modules
services:
  marytts:
    image: synesthesiam/marytts:5.2
    container_name: ${PROJECT_NAME}_mlt_maryTTS
    ports:
      - "59125:59125"
    logging:
      driver: none

  ros_ast_tts:
    build:
      context: .
    image: drz/sign_of_life/ros_nodes:latest
    container_name: speech_processing_nodes
    environment:
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
      - DIA_IP=${DIA_IP}
      - MARY_IP=${MARY_IP}
    volumes:
      - /dev:/dev
      - ./speech_processing/scripts:/catkin_ws/src/speech_processing/scripts
      - ./speech_processing/launch:/catkin_ws/src/speech_processing/launch
      #- ./initAudio.sh /initAudio.sh
      #- ./launch/speech_processing.launch:~/catkin_ws/src/speech_processing/launch/speech_processing.launch
    privileged: true
    network_mode: host
    stdin_open: true # docker run -i
    tty: true # docker run -t
    command: bash -c 'source /catkin_ws/devel/setup.bash &&
      roslaunch --wait speech_processing speech_processing.launch launch_tts_service:=true'
