# Points to the HFC config file
ontologyFile:       src/main/resources/ontology/ini/gcs.yml

# If TTS is active, ASR is suppressed
ttsStopsAsr:        true


# ########## COMPILE CONFIGURATION SETTINGS ##########
inputFile:          src/main/rudi/DialogAgent.rudi
outputDirectory:    src/main/gen-java
agentBase:          de.dfki.vondabase.BaseAgent
typeDef:            BaseAgent.rudi
checkTypes:         true
failOnError:        false
verbose:            false
rootPackage:        de.dfki.vondabase
persistentVars:     true

nameToURI:
  Agent : <dom:Actor>
  Robot : <dom:Robot>

NLG:
  de_DE:
    class: de.dfki.mlt.rudimant.agent.nlp.LanguageGenerator
    mapperProject: src/main/resources/cplanner/allrules-mapper
    generationProject: src/main/resources/cplanner/allrules
NLU:
  de_DE:
    class: de.dfki.mlt.rudimant.agent.nlp.CombinedInterpreter
    instances:
    - class: de.dfki.mlt.rudimant.agent.nlp.SrgsParser
      grammar: src/main/resources/grammars/srgs/responses.gram
      converter: src/main/resources/cplanner/srgsconv
      tokenizer:
        class: de.dfki.mlt.rudimant.agent.nlp.TrivialTokenizer
        toLower: false
        removePunctuation: true

# rudibugger settings
defaultCompileCommand: ./compile
customCompileCommands:
  Compile without maven: GraVE/bin/g2v -c config.yml
  mvn: ./compile
debugPort : 9999
filterRules : false

mqtt:
  brokerhost: localhost

automata:
  dialogue:
    sceneflow: src/main/automata/dialogue/sceneflow.xml
    # this is always relative to inputFile!
    output: dialogue
    ontology: src/main/resources/ontology/automata
