inputFile:          src/main/rudi/DialogAgent.rudi
outputDirectory:    src/main/gen-java
agentBase:          de.dfki.vondabase.BaseAgent
typeDef:            BaseAgent.rudi
ontologyFile:       data/ini/example.yml
floor:              1
checkTypes:         true
failOnError:        false
verbose:            false
GUI_enabled:        true
REST_enabled:       true
tts_blocking:       true  # set to false if you don't want that the tts output and speech bubbles on the avatar are synchronized
rootPackage:        de.dfki.vondabase
serversocket:       11666
RestAPI:
  Port:          8086
  DataLoc:       "src/main/resources/static" #tested
  #KoffiURI:      "http://192.168.182.5:8888" #gestalt
  KoffiURI:      "http://172.16.100.124:8089" #dfki
  R3:            "/workflow/cancel" #teste
  R4:            "/workflow/goto" #tested
  R5:            "/workflow/memorize_person" #tested
  R10:            "/workflow/follow_memorized_person" #tested
  R11:            "/workflow/go_home" #tested
ROSBridge:
  TTSPort:       11113
  GSCPort:       11114
  StatusPort:    11115
  SoundPort:     11116


nameToURI:
  Agent : <dom:Actor>
  Robot : <dom:Robot>

defaultCompileCommand: compile
customCompileCommands:
  Compile without maven: vondac -c config.yml
  vcompile: vondac -v -c config.yml
debugPort : 9999
TTS:
  voice: dfki-pavoque-neutral-hsmm
  backup: false
NLG:
  de:
    mapperProject: src/main/resources/grammars/cplanner/allrules-mapper
    generationProject: src/main/resources/grammars/cplanner/allrules
NLU:
  de:
    class: de.dfki.vondabase.nlu.CombinedNLU
    grammar: src/main/resources/grammars/srgs/rolli.gram
    languageCode: "deu-DEU"
    codec: "audio/L16;rate=16000"
    context_tag: "A553_C5205"
    appKey: "548871ADCA4610ECFCF29EDC6E098516975E7D6DB4BBB0368E943CCA6E8DFA3E20962C6129D34944E1817AE04791B6D15A520D6A6AF9320ACCE92EA15206489B"
    nmaid: "NMDPTRIAL_chwi02_dfki_de20180108105402"
    hostname: "wss://autotesting-azure-use2-cvt1-voice-ws.nuancemobility.net/v2"
