inputFile:          src/main/rudi/DialogAgent.rudi
outputDirectory:    src/main/gen-java
agentBase:          de.dfki.vondabase.BaseAgent
typeDef:            BaseAgent.rudi
ontologyFile:       src/main/resources/ontology/ini/gcs.yml
checkTypes:         true
failOnError:        false
verbose:            false
rootPackage:        de.dfki.vondabase

nameToURI:
  Agent : <dom:Actor>
  Robot : <dom:Robot>

NLG:
  de_DE:
    class: de.dfki.mlt.rudimant.agent.nlp.LanguageGenerator
    mapperProject: src/main/resources/cplanner/allrules-mapper
    generationProject: src/main/resources/cplanner/allrules
NLU:
  de_DE:
    class: de.dfki.mlt.rudimant.agent.nlp.CombinedInterpreter
    instances:
    - class: de.dfki.mlt.rudimant.agent.nlp.SrgsParser
      grammar: src/main/resources/grammars/srgs/responses.gram
      converter: src/main/resources/cplanner/srgsconv
      tokenizer:
        class: de.dfki.mlt.rudimant.agent.nlp.TrivialTokenizer
        toLower: false
        removePunctuation: true

# rudibugger settings
defaultCompileCommand: compile
customCompileCommands:
  Compile without maven: vondac -c config.yml
  vcompile: vondac -v -c config.yml
  mvn: mvn install
debugPort : 9999
filterRules : false

mqtt:
  brokerhost: localhost
