# Docker compose file used to load the broker, ASR, TTS, and dialogue_manager
networks:
  mlt:
    driver: bridge

services:
  broker:
    image: 'eclipse-mosquitto:2.0.15'
    networks:
      - mlt
    restart: always
    container_name: 'mqtt-broker'
    hostname: 'mqtt-broker'
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  asr_micro:
    depends_on:
      - broker
    image: 'whisper-gstreamer:${ASR_VERSION}'
    environment:
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
    command: ["/bin/sh", "-c",
              "./run_vosk.sh -c config.yml 2>&1 | tee logs/asr.log"]
    networks:
      - mlt
    container_name: 'asr_micro'
    restart: always
    hostname: 'asr_micro'
    devices:
      - /dev/snd
    group_add:
      - audio
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie
      - ./configs/respeaker_asr_config.yml:/app/config.yml:ro
      - ./whisper-gstreamer/models:/app/models
      - ${LOGDIR}/audio:/app/audio
      - ${LOGDIR}/outputs:/app/outputs
      - ${LOGDIR}:/app/logs
      - ./inputs:/app/inputs

  tts:
    depends_on:
      - broker
    image: 'tts-mqtt-server:${TTS_VERSION}'
    environment:
      PULSE_SERVER: "unix:${XDG_RUNTIME_DIR}/pulse/native"
    command: ["/bin/sh", "-c", "./run.sh config.yml 2>&1 | tee logs/asr.log"]
    networks:
      - mlt
    container_name: 'tts'
    restart: always
    hostname: 'tts'
    devices:
      - /dev/snd
    group_add:
      - audio
    volumes:
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ${HOME}/.config/pulse/cookie:/root/.config/pulse/cookie
      - ./configs/respeaker_tts_config.yml:/app/config.yml:ro
      - ./mqtt-tts/models:/app/models
      - ${LOGDIR}/audio:/app/audio
      - ${LOGDIR}/outputs:/app/outputs
      - ${LOGDIR}:/app/logs
      - ./inputs:/app/inputs

  dialog_manager:
    depends_on:
      - broker
      - asr_micro
      - tts
    build:
      context: .
    image:  drz/gcs_dialog_manager:$GCS_VERSION
    networks:
      - mlt
    container_name:  gcs_dialog_manager
    #command: ["/bin/sh", "-c", "java -jar gcs_dialog.jar 2>&1 | tee logs/gcs_dialog.log"]
    hostname: "gcs_dialog_manager"
    # environment:
    #   - DISPLAY=${DISPLAY}
    #   - ROS_MASTER_URI=${ROS_MASTER_URI}
    #   - ROS_IP=${ROS_IP}
    #   - DIA_IP=${DIA_IP}
    volumes:
      - ./configs/gcs_config.yml:/app/config.yml
      - ${LOGDIR}:/app/logs
    #privileged: true
    #network_mode: host
    restart: always
    #stdin_open: true # docker run -i
    #tty: true        # docker run -t
