version: "3"
# Docker compose file used to load the dialogue_manager
services:
  dialog_manager:
    build:
      context: .
    image:  drz/sign_of_life/dialog_manager:latest
    container_name:  drz_dialog_manager
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=${ROS_MASTER_URI}
      - ROS_IP=${ROS_IP}
      - DIA_IP=${DIA_IP}
    volumes:
      - ./config.yml:/config.yml
      - /dev:/dev
      - $HOME/.Xauthority:/root/.Xauthority:rw
    privileged: true
    network_mode: host
    restart: ${RESTART_POLICY}
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    
