#!/bin/bash
now=`date -Iseconds | sed 's/[: ]/_/g'`
LOGDIR="run${now}"
# change the following if you want the outputs somewhere else
ldir="./logs/$LOGDIR"
mkdir $ldir; touch $ldir/persistent.nt
# From asr (eventually)
mkdir $ldir/audio
mkdir $ldir/outputs
# Set current log dir for this run
mv .env .env.bak
(grep -v LOGDIR .env.bak ; echo "LOGDIR='$ldir'") > .env
docker compose up
