openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/mlt5/DialogueManager/1.0.0
info:
  description: The workflow calls these API endpoints to trigger user interaction. The UI-Avatar exposes these API endpoints.
  version: "1.0.0"
  title: Dialogue System API
  contact:
    email: christian.willms@dfki.de
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: admins
    description: Secured Admin-only calls
  - name: developers
    description: Operations available to regular developers
paths:
  /dialog/speak:
    post:
      tags:
        - developers
      summary: Speak out some text (text2speach) - D1
      operationId: tts
      description: |
        The dialog system outputs the given text as voice output via the robot's speakers.
        The TTS engine MaryTTS is used for this purpose
      responses:
        '201':
          description: valid input speech will be generated
        '400':
          description: 'invalid input, object invalid' #this should never happen
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: "Hello world"
                  description: String to generate the speech output from
  /dialog/play:
    post:
      tags:
        - developers
      summary: Play some audio file - D2
      operationId: playSound
      description: |
        The dialog system outputs the given audio via the robot's speakers.
        The audio must be provided as base64 encoded wav file content
      responses:
        '201':
          description: valid input speech will be generated
        '400':
          description: 'invalid input, object invalid - likely due to wrong encoding'
      requestBody:
        content:
          application/octet-stream:
            # any media type is accepted, functionally equivalent to `*/*`
            schema:
              # a binary file of any type
              type: string
              format: binary
  /dialog/guidme_home:
    post:
      tags:
        - developers
      summary: Ask for guiding the AGV back home (basically recovery behavior?) - D3
      operationId: askForHelp
      description: tbd
      responses:
        '201':
          description: valid input - trying to get help
        '400':
          description: 'invalid input, object invalid - likely due to wrong encoding'
  /dialog/help_elevator/entry:
    post:
      tags:
        - developers
      summary: Help to enter the elevator - D4
      operationId: helpEnterEvelvator
      description: |
        The user is asked to make free way and to open the elevator doors.
        When the user presses (or says) OK, the API method returns OK (http=200).
      responses:
        '200':
          description: we are good to go
        '500':
          description: 'no help available'
  /dialog/luggage_lost:
    post:
      tags:
        - developers
      summary: Inform the user, that the luggage felt down - D5
      operationId: luggageLost
      description: |
        The dialog system outputs a message as voice output via the robot's speakers informing the client that some of the luggage felt down.
        The TTS engine MaryTTS is used for this purpose.
      responses:
        '201':
          description: speech will be generated
        '400':
          description: 'invalid input, object invalid'
  /dialog/make_free_way:
    post:
      tags:
        - developers
      summary: people are blocking the way, asks them to step aside - D6
      operationId: makeFreeWay
      description: |
        Navigation is blocked by objects that are identified as people; the dialog system outputs a message as voice output
        via the robot's speakers asking a person or a group of people to free the way.
        The TTS engine MaryTTS is used for this purpose.
      responses:
        '200':
          description: we are good to go
        '500':
          description: 'action not successful'
  /dialog/lost_person:
    post:
      tags:
        - developers
      summary: Lost tracked person - D7
      operationId: lostPerson
      description: |
        If the AGV looses the guided person, the **API endpoint D7** is triggered to ask the user for help.
        The way how this is communicated should be left to dialog system.
      responses:
        '200':
          description: 'action successful, track person in front of AGV'
        '500':
          description: 'no reaction from client (or other persons)'
  /dialog/help_elevator/exit:
    post:
      tags:
        - developers
      summary: Help to exiting the elevator - D8
      operationId: helpExitElevator
      description: |
        The dialog system asks the user to press the number of the given level (eg. 2) on the elevator.
        After the elevator reaches its destination and the door opens, the user shall press "OK" on the UI to start the drive-out process.
        Displays a button on the UI, to inform the AGV that it reached its level of destination.
      responses:
        '200':
          description: destination level reached
        '400':
          description: 'invalid level'
        '500':
          description: 'no reaction from client'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                level:
                  type: integer
                  example: 2
                  description: the level of destination
  /dialog/new_task:
    post:
      tags:
        - developers
      summary: system received new task - D10
      operationId: newTask
      description: |
        This method is called initially when a new task is created in the system to send general information that must be made known to the dialog system so that it can do its job.
        The task definition contains the fields "id","clientName", "startPOI", "endPOI", "description". Information such as start and end point are used to send the robotic system to the corresponding positions as described in S2.
        These or other parameters could also be requested from dialog system (feasibility using ASR?; buttons are possible as well)
        Returns success if information are added as "currentTask" to the dialog managers information state.
      responses:
        '201':
          description: updated task
        '400':
          description: "invalid input, did you send a valid tesk description?"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
  /dialog/poi_reached:
    post:
      tags:
        - developers
      summary: poi reached - D11
      operationId: greeting
      description: |
        Called when the AGV has reached a POI, this might be startPOI or endPOI from D10.
        Depending on the dialogsystems internal state, the system will either greet the client and inform it about the obcoming events (load luggage and drive to endpoint) or wish the client a farewell.
        This is an essential part of *S2*.
      responses:
        '200':
          description: OK
        '500':
          description: 'no reaction from client'
components:
  schemas:
    Task:
      type: object
      required:
        - id
        - client_name
        - destination
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        client_name:
          type: string
          example: Gerd Müller
        startPOI:
          type: string
          pattern: ^\w+_\d+$
          example: 'Raum_42'
        endPOI:
          type: string
          pattern: ^\w+_\d+$
          example: "Rezeption_0"
        description:
          type: string
          description: "task description, here enums are used, can be extended/adapted as needed"
          enum:
            - Physiotherapie
            - Blutabnahme
            - Arzt
            - Zimmer_beziehen
            - Zimmer_verlassen
            - Cafeteria
          example: "Physiotherapie"