FROM ros:melodic-robot

ENV ROS_DISTRO melodic
ENV GITLAB_TOKEN oBAR1D9YTtTu1bqSo1ze

RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

ENV ROS_DISTRO melodic
ENV GITLAB_TOKEN oBAR1D9YTtTu1bqSo1ze

RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# INSTALL STUFF #######################################################################################################
RUN apt -q -qq update && \
    DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
    apt-utils \
    software-properties-common \
    nano \
    python-pip \
    python3.6\
    python3-pip\
    python3-setuptools \
    python-setuptools \
    portaudio19-dev \
    python-pyaudio \
    python3-pyaudio \
    # not sure about this
    libusb-1.0 \
    usbutils \
    unzip \
    alsa-utils \
    wget \
    apt-utils \
    alsa-base  \
    alsa-utils \
    libpulse0 \
    software-properties-common \
    libasound-dev \
    libportaudio2 \
    libportaudiocpp0 \
    python-pip

RUN apt -q -qq update && \
    DEBIAN_FRONTEND=noninteractive apt install -y --allow-unauthenticated --no-install-recommends \
    python-rosinstall \
    python-catkin-tools \
    python-catkin-pkg

RUN rosdep update

#Install python dependencies for speechrec
RUN pip install py-marytts pyaudio
#Pip wheel setup
RUN pip install wheel && pip3 install wheel
#Install python dependencies for speechrec
RUN pip install --upgrade setuptools
RUN pip install pyusb click gdown pyyaml
RUN pip3 install --upgrade setuptools
#RUN pip3 install deepspeech==0.9.3 pyyaml
#RUN pip3 install deepspeech-tflite

# INTUITIV SOFTWARE SETUP AND INSTALL ##################################################################################
#COPY usbreset script
COPY usbreset.c usbreset.c
RUN cc usbreset.c -o usbreset
COPY initAudio.sh /initAudio.sh

# clone drivers for respeaker
RUN  mkdir -p /catkin_ws/src && cd /catkin_ws/src &&  git clone --branch xavier https://chwi02:${GITLAB_TOKEN}@git.hb.dfki.de/intuitiv/mlt_modules.git

# Clean up
RUN cd /catkin_ws/src && cp -r mlt_modules/respeaker_ros . && rm -r ./mlt_modules
RUN mv /bin/sh /bin/sh_tmp && ln -s /bin/bash /bin/sh

# Install Respeaker ROS
RUN ls /opt/ros/melodic/
RUN apt -q -qq update; source /opt/ros/${ROS_DISTRO}/setup.bash; cd /catkin_ws; rosdep install --from-paths /catkin_ws/src -i -r -n -y; catkin config --init; catkin build respeaker_ros 

#SETUP
RUN apt autoremove
RUN touch /root/.bashrc &&  echo "source /catkin_ws/devel/setup.bash \n" >> /root/.bashrc
RUN rm -rf /var/lib/apt/lists/*

#ENTRYPOINT ["/ros_entrypoint.sh"]
CMD ["bash"]